# Generated by Django 5.2.9 on 2026-02-02 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inquiry',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_image',
            field=models.ImageField(
                upload_to='site/hero/',
                blank=True,
                null=True
            ),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='projects',
                to='website.category'
            ),
        ),
        migrations.AlterField(
            model_name='project',
            name='cover_image',
            field=models.ImageField(
                upload_to='projects/covers/'
            ),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(
                upload_to='projects/images/'
            ),
        ),
    ]
