# Generated by Django 5.2.9 on 2026-02-04 16:26

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_inquiry_options_sitesettings_hero_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='cover_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Project Cover'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Project Image'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Hero Image'),
        ),
    ]
