# Generated by Django 5.2.9 on 2026-02-05 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(
                upload_to='categories/',
                blank=True,
                null=True
            ),
        ),
    ]
